alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gb='git branch'
alias gdu='git diff'
alias gdc='git diff --cached'
alias go='git checkout'
alias glo='git log --pretty=oneline'
alias glod='git log --pretty=oneline --decorate'
alias gsi='git submodule init'
alias gsu='git submodule update'

alias sx='screen -x '
alias sl='screen -ls'
